name: Build release zip

on:
  workflow_dispatch:
  push:
   branches:
    - trunk

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node version and npm cache
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Cache vendor
        id: cache-composer
        uses: actions/cache@v3
        env:
          cache-name: cache-vendor
        with:
          path: |
            vendor
            ~/.composer/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.json') }}

      - name: Install Composer dependencies
        if: steps.cache-vendor.outputs.cache-hit != 'true'
        run: composer install --no-dev

      - name: Install Node dependencies
        run: npm ci --no-optional

      - name: Build plugin
        run: npm run build

      - name: Generate ZIP file
        uses: 10up/action-wordpress-plugin-build-zip@stable
